apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
 name: hello-certificate
spec:
 secretName: hello-certificate-key-pair
 isCA: true
 issuerRef:
   name: hello-certificate-issuer
   kind: Issuer
 commonName: "hello.certificate"
 dnsNames:
 - hello.certificate